<input
placeholder="Input"
type="text"
class="form-control"
id="original_decoded_string"
oninput="$('#encoded_output_string')[0].value=btoa($('#original_decoded_string')[0].value);">
<input
placeholder="Output"
type="text"
class="form-control"
id="encoded_output_string"
disabled>
