<input
placeholder="Input"
type="number"
class="form-control"
id="original_dec2_string"
oninput="$('#output_bin_string')[0].value=parseInt($('#original_dec2_string')[0].value).toString(2);">
<input
placeholder="Output"
type="text"
class="form-control"
id="output_bin_string"
disabled>
