<input
placeholder="Input"
type="text"
class="form-control"
id="original_dec_string"
oninput="$('#output_hex_string')[0].value=parseInt($('#original_dec_string')[0].value).toString(16).toUpperCase();">
<input
placeholder="Output"
type="text"
class="form-control"
id="output_hex_string"
disabled>
