<input
placeholder="Input"
type="text"
class="form-control"
id="original_hex_string"
oninput="$('#output_dec_string')[0].value=parseInt($('#original_hex_string')[0].value,
16);">
<input
placeholder="Output"
type="text"
class="form-control"
id="output_dec_string"
disabled>
